/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsVeterinaryRouteImport } from './routes/solutions/veterinary'
import { Route as SolutionsMedicalRouteImport } from './routes/solutions/medical'
import { Route as SolutionsEngineeringRouteImport } from './routes/solutions/engineering'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsVeterinaryRoute = SolutionsVeterinaryRouteImport.update({
  id: '/veterinary',
  path: '/veterinary',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsMedicalRoute = SolutionsMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsEngineeringRoute = SolutionsEngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/engineering': typeof SolutionsEngineeringRoute
  '/solutions/medical': typeof SolutionsMedicalRoute
  '/solutions/veterinary': typeof SolutionsVeterinaryRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/projects': typeof ProjectsRoute
  '/solutions/engineering': typeof SolutionsEngineeringRoute
  '/solutions/medical': typeof SolutionsMedicalRoute
  '/solutions/veterinary': typeof SolutionsVeterinaryRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/engineering': typeof SolutionsEngineeringRoute
  '/solutions/medical': typeof SolutionsMedicalRoute
  '/solutions/veterinary': typeof SolutionsVeterinaryRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/projects'
    | '/solutions'
    | '/solutions/engineering'
    | '/solutions/medical'
    | '/solutions/veterinary'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/projects'
    | '/solutions/engineering'
    | '/solutions/medical'
    | '/solutions/veterinary'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/projects'
    | '/solutions'
    | '/solutions/engineering'
    | '/solutions/medical'
    | '/solutions/veterinary'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  ProjectsRoute: typeof ProjectsRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/veterinary': {
      id: '/solutions/veterinary'
      path: '/veterinary'
      fullPath: '/solutions/veterinary'
      preLoaderRoute: typeof SolutionsVeterinaryRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/medical': {
      id: '/solutions/medical'
      path: '/medical'
      fullPath: '/solutions/medical'
      preLoaderRoute: typeof SolutionsMedicalRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/engineering': {
      id: '/solutions/engineering'
      path: '/engineering'
      fullPath: '/solutions/engineering'
      preLoaderRoute: typeof SolutionsEngineeringRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsEngineeringRoute: typeof SolutionsEngineeringRoute
  SolutionsMedicalRoute: typeof SolutionsMedicalRoute
  SolutionsVeterinaryRoute: typeof SolutionsVeterinaryRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsEngineeringRoute: SolutionsEngineeringRoute,
  SolutionsMedicalRoute: SolutionsMedicalRoute,
  SolutionsVeterinaryRoute: SolutionsVeterinaryRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  ProjectsRoute: ProjectsRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
